---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-opr8r-opr8r-io-v1-opr8r
  failurePolicy: Fail
  name: mopr8r-v1.kb.io
  rules:
  - apiGroups:
    - opr8r.opr8r.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opr8rs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-opr8r-opr8r-io-v1-opr8r
  failurePolicy: Fail
  name: vopr8r-v1.kb.io
  rules:
  - apiGroups:
    - opr8r.opr8r.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opr8rs
  sideEffects: None
