# This rule is not used by the project opr8r itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over opr8r.opr8r.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opr8r
    app.kubernetes.io/managed-by: kustomize
  name: opr8r-admin-role
rules:
- apiGroups:
  - opr8r.opr8r.io
  resources:
  - opr8rs
  verbs:
  - '*'
- apiGroups:
  - opr8r.opr8r.io
  resources:
  - opr8rs/status
  verbs:
  - get
