terraform {
  required_version = ">= 1.0"

  # Using local backend for simplicity - no S3 required
  backend "local" {
    path = "/tmp/terraform-{{ .Namespace }}-{{ .Name }}.tfstate"
  }

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Generate a random string
resource "random_string" "value" {
  length  = {{ .Length }}
  special = lookup(var.custom_vars, "special", "true") == "true"
  upper   = lookup(var.custom_vars, "upper", "true") == "true"
  lower   = lookup(var.custom_vars, "lower", "true") == "true"
  numeric = lookup(var.custom_vars, "numeric", "true") == "true"
}

# Create a local file with the random value
resource "local_file" "output" {
  content  = <<-EOT
    Generated by opr8r
    Namespace: {{ .Namespace }}
    Name: {{ .Name }}
    Random Value: ${random_string.value.result}
    Timestamp: ${timestamp()}
  EOT
  filename = "/tmp/opr8r-{{ .Namespace }}-{{ .Name }}.txt"
}

# Variables for custom configuration
variable "custom_vars" {
  description = "Custom variables from SimpleResource spec"
  type        = map(string)
  default     = {
    {{- range $key, $value := .Vars }}
    "{{ $key }}" = "{{ $value }}"
    {{- end }}
  }
}

# Putting this here so its easier to test
# Makes it easier to see the jobs run, monitor the logs in real time,
# and ensure we dont hit race conds
resource "time_sleep" "wait_one_minute" {
  depends_on      = [local_file.output]
  create_duration = "60s"
}

# Outputs
output "random_value" {
  description = "The generated random string"
  value       = random_string.value.result
}

output "file_path" {
  description = "Path to the generated file"
  value       = local_file.output.filename
}

output "file_content" {
  description = "Content of the generated file"
  value       = local_file.output.content
}

output "length" {
  description = "Length of the random string"
  value       = random_string.value.length
}
